# Generated by Django 2.1.4 on 2019-01-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotes',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
